"""add_bank_code_iban

Revision ID: 0002
Revises: init_0001
Create Date: 2024-11-05 06:55:16.317938

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "init_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice_suppliers",
        sa.Column("bank_code", sa.String(length=10), nullable=True),
    )
    op.add_column(
        "invoice_suppliers",
        sa.Column("iban", sa.String(length=34), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoice_suppliers", "iban")
    op.drop_column("invoice_suppliers", "bank_code")
    # ### end Alembic commands ###
