"""First revision

Revision ID: 0003_user_update
Revises: 0002
Create Date: 2024-11-28 08:33:45.394055

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_user_update"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "email",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=255),
        nullable=True,
    )
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.drop_column("user", "is_verified")
    op.drop_column("user", "is_superuser")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user",
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1024),
        nullable=False,
    )
    op.alter_column(
        "user",
        "email",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=320),
        nullable=False,
    )
    # ### end Alembic commands ###
