"""Add order number to invoice

Revision ID: 0009
Revises: 0008
Create Date: 2025-07-20 19:19:41.951105

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice_invoices",
        sa.Column("order_number", sa.String(length=20), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("invoice_invoices", "order_number")
    # ### end Alembic commands ###
